# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIUTestExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIUTestExample

  target 'UIUTestExampleTests' do
    inherit! :search_paths
    pod 'UIUTest'
    # Pods for testing
  end

end
